### ISSUE TITLE
What is the relationship between this and DPVS?

### ISSUE THREAD

**Issue by ygm521** [intel/high-density-scalable-load-balancer#2]
What is the relationship between this and DPVS? Can it be understood as a reference implementation of DPVS, rather than being developed based on DPVS?

**Comment by HongjunNi** [comment]
High-Density Scalable Load Balancer(HDSLB) is a high performance Layer-4 load balancer based on DPVS and DPDK(Data Plane Development Kit). It refactors and optimizes the performance of key data plane features, supports 100 Million+ sessions and session sync within LB (load balancer) cluster.
