### ISSUE TITLE
How to activate DLB flow

### ISSUE THREAD

**Issue by rkesters** [intel/high-density-scalable-load-balancer#7]
I want to replicate the experiment done in the Accelerating Elephant FLow paper. But it is unclear on how to run HDSLB with and without Intel DLB active. Can you provide documentation or links to code that activates the DLB queues?

**Comment by PanZhangg** [comment]
@rkesters  Please send an email to pan1.zhang@intel.com using your company mail address, if there's an active CNDA between Intel and your company, I can then share you the DLB code patch of HDSLB and related documentation.
